'use client';

import { useEffect, useRef } from 'react';
import { gsap } from 'gsap';

export default function TermsPage() {
  const pageRef = useRef(null);

  useEffect(() => {
    const ctx = gsap.context(() => {
      gsap.fromTo(
        pageRef.current,
        { opacity: 0, y: 20 },
        { opacity: 1, y: 0, duration: 1, ease: 'power3.out' }
      );
    }, pageRef);

    return () => ctx.revert();
  }, []);

  return (
    <div ref={pageRef} className="container mx-auto max-w-4xl py-12 md:py-20 px-4">
      <h1 className="text-3xl md:text-4xl font-bold mb-8 text-transparent bg-clip-text bg-gradient-to-r from-white to-gray-400">Terms and Conditions for Vizionary</h1>
      <p className="text-muted-foreground mb-6">Effective Date: September 7, 2025</p>

      <div className="space-y-6 text-foreground/80">
        <p>Welcome to Vizionary! These Terms and Conditions ("Terms") govern your access to and use of the Vizionary website, application, and services (collectively, the "Service"). Please read these Terms carefully before using the Service.</p>
        <p>By accessing or using the Service, you agree to be bound by these Terms. If you disagree with any part of the terms, you may not access the Service.</p>
        
        <section className="space-y-2">
            <h2 className="text-2xl font-semibold text-primary pt-4">1. Description of Service</h2>
            <p>Vizionary is a computer vision application that converts live or uploaded visual inputs (such as webcam streams, images, or videos) into human-readable text descriptions ("Captions"). The Service is designed to be ultra-efficient and operate in constrained computing environments. The descriptions are generated by an Artificial Intelligence (AI) model.</p>
        </section>

        <section className="space-y-2">
            <h2 className="text-2xl font-semibold text-primary pt-4">2. Acceptance of Terms</h2>
            <p>Your access to and use of the Service is conditioned on your acceptance of and compliance with these Terms. These Terms apply to all visitors, users, and others who access or use the Service.</p>
        </section>

        <section className="space-y-2">
            <h2 className="text-2xl font-semibold text-primary pt-4">3. User-Provided Content</h2>
            <p>To use the Service, you may provide visual data by activating your camera or uploading files ("User Content"). You retain all ownership rights to your User Content. However, by providing User Content to the Service, you grant Vizionary a worldwide, non-exclusive, royalty-free, sublicensable, and transferable license to use, process, reproduce, and display that User Content solely for the purpose of operating, providing, and improving the Service.</p>
            <p>This license is limited in scope. The processing of your User Content is transient. We do not store your video streams or uploaded files on our servers after the captioning process is complete, unless explicitly stated otherwise.</p>
        </section>

        <section className="space-y-2">
            <h2 className="text-2xl font-semibold text-primary pt-4">4. Acceptable Use Policy</h2>
            <p>You agree not to use the Service to:</p>
            <ul className="list-disc list-inside pl-4 space-y-2">
                <li>Stream, upload, or generate captions for any content that is unlawful, harmful, threatening, abusive, harassing, defamatory, vulgar, obscene, or invasive of another's privacy.</li>
                <li>Transmit any content that infringes upon any patent, trademark, trade secret, copyright, or other proprietary rights of any party.</li>
                <li>Stream or upload any content of individuals who have not consented to being recorded or having their image processed.</li>
                <li>Transmit any material that contains software viruses or any other computer code, files, or programs designed to interrupt, destroy, or limit the functionality of any computer software or hardware.</li>
                <li>Interfere with or disrupt the Service or servers or networks connected to the Service.</li>
            </ul>
            <p>We reserve the right to investigate and/or terminate your access to the Service without notice for any violation of this policy.</p>
        </section>

        <section className="space-y-2">
            <h2 className="text-2xl font-semibold text-primary pt-4">5. AI-Generated Content and Disclaimers</h2>
            <p>The captions generated by Vizionary are created by a Vision Language Model (VLM). You acknowledge and agree to the following:</p>
             <ul className="list-disc list-inside pl-4 space-y-2">
                <li><strong>No Guarantee of Accuracy:</strong> The AI-generated Captions may contain errors, inaccuracies, or omissions. They may be incomplete, biased, or not representative of the actual visual content.</li>
                <li><strong>Not for Critical Use:</strong> The Service is provided for informational, educational, and entertainment purposes only. You must not rely on the Captions for any critical, safety-related, security, medical, or life-and-death decisions. Always use your own judgment and verify information through other means when necessary.</li>
                <li><strong>Potential for Offensive Content:</strong> While we strive to moderate the output, the AI may occasionally generate content that could be considered offensive or inappropriate. You use the Service at your own risk.</li>
            </ul>
        </section>

        <section className="space-y-2">
            <h2 className="text-2xl font-semibold text-primary pt-4">6. Intellectual Property</h2>
            <p>All rights, title, and interest in and to the Service itself, including its source code, user interface, logos, text, graphics, and other content created by Vizionary (excluding User Content and AI-generated Captions), are and will remain the exclusive property of Vizionary and its licensors.</p>
        </section>

        <section className="space-y-2">
            <h2 className="text-2xl font-semibold text-primary pt-4">7. Privacy</h2>
            <p>Your privacy is important to us. Our Privacy Policy explains how we collect, use, and share information about you. By using the Service, you agree to the collection and use of information in accordance with our Privacy Policy.</p>
        </section>

        <section className="space-y-2">
            <h2 className="text-2xl font-semibold text-primary pt-4">8. Disclaimer of Warranties</h2>
            <p>THE SERVICE IS PROVIDED ON AN "AS IS" AND "AS AVAILABLE" BASIS. VIZIONARY EXPRESSLY DISCLAIMS ALL WARRANTIES OF ANY KIND, WHETHER EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT.</p>
            <p>WE DO NOT WARRANT THAT THE SERVICE WILL MEET YOUR REQUIREMENTS, BE UNINTERRUPTED, TIMELY, SECURE, OR ERROR-FREE, OR THAT THE CAPTIONS WILL BE ACCURATE OR RELIABLE.</p>
        </section>

        <section className="space-y-2">
            <h2 className="text-2xl font-semibold text-primary pt-4">9. Limitation of Liability</h2>
            <p>IN NO EVENT SHALL VIZIONARY, ITS DIRECTORS, EMPLOYEES, OR PARTNERS BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, INCLUDING WITHOUT LIMITATION, LOSS OF PROFITS, DATA, USE, GOODWILL, OR OTHER INTANGIBLE LOSSES, RESULTING FROM (I) YOUR ACCESS TO OR USE OF OR INABILITY TO ACCESS OR USE THE SERVICE; (II) ANY AI-GENERATED CAPTIONS; (III) ANY CONDUCT OR CONTENT OF ANY THIRD PARTY ON THE SERVICE; OR (IV) UNAUTHORIZED ACCESS, USE, OR ALTERATION OF YOUR TRANSMISSIONS OR CONTENT, WHETHER BASED ON WARRANTY, CONTRACT, TORT (INCLUDING NEGLIGENCE), OR ANY OTHER LEGAL THEORY, WHETHER OR NOT WE HAVE BEEN INFORMED OF THE POSSIBILITY OF SUCH DAMAGE.</p>
        </section>

        <section className="space-y-2">
            <h2 className="text-2xl font-semibold text-primary pt-4">10. Termination</h2>
            <p>We may terminate or suspend your access to the Service immediately, without prior notice or liability, for any reason whatsoever, including without limitation if you breach the Terms. Upon termination, your right to use the Service will immediately cease.</p>
        </section>

        <section className="space-y-2">
            <h2 className="text-2xl font-semibold text-primary pt-4">11. Changes to Terms</h2>
            <p>We reserve the right, at our sole discretion, to modify or replace these Terms at any time. We will provide notice of any changes by posting the new Terms on this page. By continuing to access or use our Service after those revisions become effective, you agree to be bound by the revised terms.</p>
        </section>

        <section className="space-y-2">
            <h2 className="text-2xl font-semibold text-primary pt-4">12. Governing Law</h2>
            <p>These Terms shall be governed and construed in accordance with the laws of the State of Delaware, United States, without regard to its conflict of law provisions.</p>
        </section>

        <section className="space-y-2">
            <h2 className="text-2xl font-semibold text-primary pt-4">13. Contact Us</h2>
            <p>If you have any questions about these Terms, please contact us at: <a href="mailto:satwiks788@gmail.com" className="text-primary hover:underline">satwiks788@gmail.com</a>.</p>
        </section>
      </div>
    </div>
  );
}
